//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webIDZ.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatchesView
    {
        public System.DateTime DateCatch { get; set; }
        public string zone { get; set; }
        public string stations { get; set; }
        public string Biotope { get; set; }
        public string Distrtict { get; set; }
        public string Place { get; set; }
        public int Traps_Amount { get; set; }
        public int Catched_Amount { get; set; }
        public Nullable<decimal> in_target { get; set; }
        public string Comments { get; set; }
    }
}
