//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webIDZ.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MiceCatchEntities : DbContext
    {
        public MiceCatchEntities()
            : base("name=MiceCatchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catch> Catch { get; set; }
        public virtual DbSet<Mouse> Mouse { get; set; }
        public virtual DbSet<Pregnancy> Pregnancy { get; set; }
        public virtual DbSet<Stations> Stations { get; set; }
        public virtual DbSet<Types> Types { get; set; }
        public virtual DbSet<Zones> Zones { get; set; }
        public virtual DbSet<CatchesView> CatchesView { get; set; }
        public virtual DbSet<ProtocolsView> ProtocolsView { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
