//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webIDZ.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mouse
    {
        public System.Guid ID_Mouse { get; set; }
        public int Catch_ID { get; set; }
        public int Type_ID { get; set; }
        public int Pregnancy_ID { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public int Embryos_Amount { get; set; }
    
        public virtual Catch Catch { get; set; }
        public virtual Pregnancy Pregnancy { get; set; }
        public virtual Types Types { get; set; }
    }
}
